language: objective-c
before_install:
  - brew update
  - which ios-sim || brew install ios-sim
install: true
env:
  global:
    - ONLY_ACTIVE_ARCH=NO
  matrix:
    - IOS_VERSION=7.0.3
    - IOS_VERSION=7.1
    - IOS_VERSION=8.0
script:
  - xcodebuild -project Demo/SZTextView.xcodeproj -scheme SZTextView -sdk iphonesimulator -configuration Debug -destination "platform=iOS Simulator,name=iPhone 4s,OS=$IOS_VERSION" clean test
